### ISSUE TITLE
Option to use/reference content of own website

### ISSUE THREAD

**Issue by nekromoff** [knub/wordbol#2]
Hello,

is there an option to configure it to not to use Wikipedia but the website/Wordpress installation instead?

E.g. I don't want it to reference Wikipedia in the content, but rather the content of the website it is running on / Wordpress website. I have not studies the code yet, but this would require analysis / search of the pre-existing content in Wordpress DB and using that.

**Comment by knub** [comment]
Hi,

I am not sure what you mean by that.
Let me give you a short introduction in how the linking process works.
Wordbol links to certain well defined entities (e.g. places, persons, organizations). For that, it uses a knowledge base, concretely DBpedia. DBpedia contains a list of entities and labels for them.
These labels are compared to what was found in the text, and if that matches, the entity is returned.
For example, if your text contains "Barack Obama", Stanbol finds an entity http://dbpedia.org/page/Barack_Obama in DBpedia, and links to that.

Now I do not understand how this should work on blog posts. Blog posts are not one narrowly defined entity.
So how do you want to recognize, which part of the input text should link to which article in your blog?

In general, you can link to entities in the Stanbol EntityHub by configuring your own enhancement engine for that and use it in your enhancement chain [1]. However, your entities in the entity hub (which could be the blog posts) would probably need to define labels, as mentioned above.

Cheers
Stefan

[1] See https://stanbol.apache.org/docs/trunk/components/entityhub/ for the Stanbol EntityHub and
            http://stanbol.apache.org/docs/trunk/components/enhancer/engines/entityhublinking for how to configure an entity hub linking engine.

**Comment by nekromoff** [comment]
Hello,

I meant via text analysis and using titles - e.g. if I am mentioning
Copenhagen and there is article on Copenhagen (titled: Copenhagen), it
would link to it.

Indeed, there is no official entity defined, but it would be easy. Anyway,
I might try later to create something like that for my needs in WP.
